version: '3.3'
services:
  redis1:
    # 启动之后的容器名称
    container_name: redis-node-1
    # 使用哪种镜像
    image: 'redis'
    env_file:
      - ./.env
    # 端口映射
    ports:
      - 10001:6379
    networks:
        mynetwork:
          ipv4_address: 172.10.0.2
    volumes:
      # 容器的data映射到宿主机
      - ${PWD}/master/redis.conf:/etc/redis.conf
      # 加载配置文件
      - /data/redis/${MASTER_PORT}:/data
    # 启动redis的时候指定配置文件
    command: redis-server /etc/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点2
  redis2:
    container_name: redis-node-2
    # 使用哪种镜像
    image: 'redis'
    env_file:
      - ./.env
    # 端口映射
    ports:
     - 10002:6379
    networks:
      mynetwork:
        ipv4_address: 172.10.0.4
    volumes:
      # 容器的data映射到宿主机
      - ${PWD}/slave/redis.conf:/etc/redis.conf
      # 加载配置文件
      - /data/redis/${NODE_PORT}:/data
    # 启动redis的时候指定配置文件
    command: redis-server /etc/redis.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
  # 节点3
  redis3:
    container_name: redis-node-3
    # 使用哪种镜像
    image: 'redis'
    # 端口映射
    ports:
       - 10003:26379
    env_file:
      - ./.env
    networks:
        mynetwork:
          ipv4_address: 172.10.0.4
    volumes:
      # 容器的data映射到宿主机
      - ${PWD}/sentinel/sentinel.conf:/etc/sentinel.conf
      # 加载配置文件
      - /data/redis/${SENTINEL_PORT}:/data
    # 启动redis的时候指定配置文件
    command: redis-sentinel /etc/sentinel.conf
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
networks:
  # 创建集群网络，在容器之间通信
  mynetwork:
    ipam:
      config:
        - subnet: 172.10.0.0/16